import { Inter } from 'next/font/google'

import './globals.css'
import Header from '../components/Header'
import Sidebar from '../components/Sidebar'
import ClientProvider from '../components/ClientProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Amazon Web Scraper',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='flex bg-[#F7FBFF] h-screen'>
        {/* Herr we will have the Sidebar */}
        <Sidebar />

        <ClientProvider>
          <main className='p-10 max-w-7xl w-full mx-auto overflow-y-auto'>
            <Header />

            {/* Below signifies the main page */}
            {children}
          </main>
        </ClientProvider>
      </body>
    </html>
  )
}
